=== miguelmig/DWeb2019/Guiao2/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT PR (header,work-team,abstract,deliverables) >

<!ELEMENT header (key-name, titulo, sub-titulo?, data-inicio, data-fim, supervisor) >
<!ELEMENT key-name (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT sub-titulo (#PCDATA)>
<!ELEMENT data-inicio (#PCDATA)>
<!ELEMENT data-fim (#PCDATA)>
<!ELEMENT supervisor (supervisor-nome)>
<!ELEMENT supervisor-nome (#PCDATA) >
<!ATTLIST supervisor link CDATA #FIXED "http://www.di.uminho.pt/~jcr">

<!ELEMENT work-team (work-element+)>
<!ELEMENT work-element (work-nr, work-name, work-mail, work-git?)>
<!ELEMENT work-nr (#PCDATA)>
<!ELEMENT work-name (#PCDATA)>
<!ELEMENT work-mail (#PCDATA)>
<!ELEMENT work-git (#PCDATA)>

<!ELEMENT abstract (#PCDATA|i|b|ref)*>

<!ELEMENT i (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT ref (#PCDATA)>
<!ATTLIST ref src CDATA #REQUIRED>

<!ELEMENT deliverables (deliverable*)>
<!ELEMENT deliverable (#PCDATA)>
<!ATTLIST deliverable src CDATA #REQUIRED>

=== miguelmig/DWeb2019/Guiao2/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PR SYSTEM "file:/C:/Users/migue/Dropbox/Universidade/Desenvolvimento%20Web/Guiao2/PR.dtd">
<PR>
    <header>
        <key-name>DAW_MEI2019_TPCS</key-name>
        <titulo>Esquemas DTD e queries XPath</titulo>
        <sub-titulo>Inserido no contexto do TPC2</sub-titulo>
        <data-inicio>Setembro 2019</data-inicio>
        <data-fim>Setembro 2019</data-fim>
        <supervisor link="http://www.di.uminho.pt/~jcr">
            <supervisor-nome>José Carlos Ramalho</supervisor-nome>
        </supervisor>
    </header>
    <work-team>
        <work-element>
            <work-nr>PG41088</work-nr>
            <work-name>Miguel Pimentel de Oliveira</work-name>
            <work-mail>pg41088@alunos.uminho.pt</work-mail>
        </work-element>
    </work-team>
    <abstract>
		Com a intenção de utilizar o modelo <ref src="https://en.wikipedia.org/wiki/Open_Archival_Information_System">OAIS</ref> o professor pediu-nos que 
			especificássemos o <i>SIP</i> de modo a facilitar as entregas de TPCs no futuro.
			Para tal foi necessário criar o ficheiro <b>PR.dtd</b> com base no <ref src="http://www4.di.uminho.pt/~jcr/XML/didac/xmldocs/PR.htm">exemplo</ref> 
			que nos foi fornecido. 
		O professor pediu também para ser feito o exercício 6 e 7 da <ref src="http://www4.di.uminho.pt/~jcr/XML/CURSOS/PED2008/fichas/ficha3/index.html">Ficha 3</ref>, relacionado com <b>DTDs</b> e queries de <b>XPath</b> 
		</abstract>
    <deliverables>
        <deliverable src="PR.dtd">Ficheiro especificação(.dtd) do ficheiro PR</deliverable>
        <deliverable src="queries.txt">Queries XPath da Ficha 3 Exercício 6</deliverable>
        <deliverable src="arq.dtd">Ficheiro especificação(.dtd) da Ficha 3 Exercício 7</deliverable>
    </deliverables>
</PR>
